---
- name: data-application
  hosts: data-application
  remote_user: ubuntu
  become: yes

  pre_tasks:
  - name: Execute the script for mounting device
    script: ../scripts/mount_device.sh

  roles:
  - ldap-agent
  - node-exporter

  vars:
    service_name : "data-application"
    dns_name_of_server : "data-application.a2i.prod"
