---

################## Ansible play for node infra_tools #####################

- name: Install and configure infra tools like zk-server and CA-server
  hosts: infra_tools
  remote_user: ubuntu
  become: yes
  pre_tasks:
  - name: Execute the script for mounting device
    script: ../scripts/mount_device.sh

  roles:
  - java
  - nifi-toolkit
  - zookeeper
  - install_env
  - filebeat
  - node-exporter

  vars:
    service_name             : "infra-tools"
    zk_server_id             : "1"
    env_dns                  : "a2i.infra"
    is_ca_server             : "true"
    ca_server_dn             : "cn=ca-server.a2i.infra,ou=users,dc=a2i,dc=infra"
    ca_server_hostname       : "ca-server.a2i.infra"
    dns_name_of_server       : "infra-tools.a2i.infra"
