---
# tasks file for filebeat setup

- name: Create temp supporting directories on remote
  file:
    path: /etc/filebeat-temp/
    state: directory

- name: Copy filebeat binaries to remote host
  copy:
    src: "./binaries/filebeat-oss.tar.gz"
    dest: /etc/filebeat-temp/
    mode: '1440'

- name: Create supporting directories on remote
  file:
    path: /etc/filebeat/
    state: directory

- name: Extracting the filebeat binary files to temp directory
  unarchive:
    src: "/etc/filebeat-temp/filebeat-oss.tar.gz"
    dest: "/etc/filebeat-temp/"
    remote_src: yes

- name: Copy filebeat binary files to /etc/filebeat location
  copy:
    src: "/etc/filebeat-temp/filebeat-7.9.2-linux-x86_64/"
    dest: "/etc/filebeat/"
    remote_src: yes
    directory_mode: yes

- name: Copy reference filebeat.yml
  template:
    src: filebeat.yml
    dest: "/etc/filebeat/filebeat.yml"

- name: Clean-up
  file:
    state: absent
    path: "/etc/filebeat-temp/"
