FROM node:10.12-slim
ENV PORT 3001
EXPOSE 3001
WORKDIR /usr/src/app
COPY . .
RUN apt update
RUN apt install -y bzip2 libfontconfig
RUN rm -rf node_modules
RUN npm install phantomjs-prebuilt 
RUN npm install
RUN npm run PHASE
ENTRYPOINT ["sh", "-c", "npm run server"]