---
# vars file for mongodb
installation:
  key_serv: hkp://keyserver.ubuntu.com:80
  key: E52529D4
  apt_repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse
is_clustered: true
replicaset:
  name: rs0
  host: localhost
  members:
    - mongodb1:27017
    - mongodb2:27017
    - mongodb3:27017
adminUser:
  name: adminUser
  database: admin
  password: password
  roles: clusterAdmin, userAdminAnyDatabase, dbAdminAnyDatabase, readWriteAnyDatabase