---
# defaults file for postgresql

postgres:
      key_url: deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main
      repo:url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      pkg:
      - postgresql 
      - postgresql-contrib