---
# tasks file for ldap-agent

- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes

- name: 'Install required packages'
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libnss-ldap
    - libpam-ldap
    - sssd

- name: Configure the sssd.conf
  template:
    src: sssd.conf
    dest: /etc/sssd/sssd.conf
    mode: 0400

- name: configure the server cert
  template:
    src: server.crt
    dest: /etc/ldap/server.crt

#- name: Get the cert from an RDP port
#  get_certificate:
#    host: "{{ ldap_agent.ldap_server_url }}"
#    port: 389
#  delegate_to: localhost
#  run_once: true
#  register: cert

#- name: create cert on filesystem
#copy:
#    content: "{{ cert }}"
#    dest: /etc/ldap/server.crt

- name: Update the sshd configuration to enable password login
  replace:
    path: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'

- name: add to ansible hosts file
  lineinfile:
    dest: "/etc/pam.d/common-session"
    insertafter: 'session(.*)required(.*)pam_permit.so(.*)'
    line: "session required     pam_mkhomedir.so skel=/etc/skel/"

- name: restart the sshd and sssd services
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - sshd
    - sssd
