---
# defaults file for prometheus
node_exporter_download_url: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz
node_exporter_version: 0.18.1
