---
- name: elk
  hosts: elk
  remote_user: ubuntu
  become: yes

  pre_tasks:
  - name: Execute the script for mounting device
    script: ../scripts/mount_device.sh

  roles:
  - install_env
  - elk
  - zookeeper
  - filebeat
  - node-exporter

  vars:
    aws_region: eu-west-1
    environment: stage
    platform: a2i
    service_name : "elk"
    dns_name_of_server : "elk.a2i.infra"
    zk_server_id  : "3"
