galaxy_info:
  author: "Yogesh Patil"
  company: TTN
  license: BSD
  min_ansible_version: 1.4
  platforms:
   - name: EL
     versions:
      - 5
      - 6
      - 7
   - name: Ubuntu
     versions:
      - precise
      - trusty
      - xenial
      - bionic
  categories:
   - system
dependencies: []
