---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Pull ldap root password from SSM
  debug: msg="{{ lookup('aws_ssm', '{{ openldap_server_rootuserpath_ssm }}' ) }}"
  register: openldap_server_rootpw
  delegate_to: localhost

- name: Install the openldap and required Packages for Ubuntu
  apt: name={{ openldap_server_pkgs }} state=present update_cache=yes
  environment: '{{ env }}'
  when: ansible_os_family == 'Debian'

- name: Install the phpldapadmin package for GUI
  apt: name={{ phpldapadmin_pkgs }} state=present update_cache=yes
  environment: '{{ env }}'
  when: ansible_os_family == 'Debian'


- name: Delete the configuration directory
  file: path={{ openldap_server_app_path }}/slapd.d state=absent

- name: Generate the root password for ldap
  shell: slappasswd -s {{ openldap_server_rootpw.msg }}
  register: root_password
  no_log: true

- name: Copy the slapd.conf configuration file
  template: src=slapd.conf_ubuntu.j2 dest={{ openldap_server_app_path }}/slapd.conf
  when: ansible_os_family == "Debian"
  notify:
   - restart slapd

- name: Copy the ldap.conf configuration file
  template: src=ldap.conf.j2 dest={{ openldap_server_app_path }}/ldap.conf

- name: Copy the phpldapadmin.php configuration file
  template: src=phpldapadmin.php dest={{ phpldapadmin_config_path }}/config.php
  when: ansible_os_family == "Debian"

- name: Copy the phpldapadmin-apache2.conf configuration file
  template: src=phpldapadmin-apache2.conf dest={{ apache2_config_path }}/000-default.conf
  when: ansible_os_family == "Debian"
  notify:
   - restart apache2
