---
- name: recommend to use with aws_ssm lookup plugin
  debug: msg="{{ lookup('aws_ssm', '{{ openldap_server_rootuserpath_ssm }}') }}"
  register: openldap_pass
#  debug: msg="{{ openldap_server_rootuserpath_ssm }}"

- name: var=openldap_pass.msg
  debug: msg="{{ openldap_pass.msg }}"

- name: Pull aws region value
  debug: msg="{{ aws_region }}"
  register: aws_region_value

- name: var=openldap_pass.msg
  debug: msg="{{ aws_region_value.msg }}"
