insert into om_dbo.OM_SALES_ORDER (
select
			SOR_ID_SEQ             ::bigint,
			BUS_SEQ                ::int,
			LOC_SEQ                ::int,
			CST_SEQ                ::bigint,
			ORT_SEQ                ::smallint,
			ORC_SEQ                ::bigint,
			PTM_SEQ                        ::int,
			SOR_SALE_TYPE          ::VARCHAR(30),
			SOR_SA_SEQ             ::int,
			SOR_ORDER_NO           ::VARCHAR(30),
			cast(SOR_ORDER_DATE as timestamp) AS SOR_ORDER_DATE,
			SOR_ORDER_STATUS       ::VARCHAR(30),
			SOR_JPL_SEQ                    ::VARCHAR(30),
			SOR_LINE_COUNT         ::smallint,
			SOR_TOTAL_QUANTITY     ::bigint,
			SOR_TOTAL_VALUE        ::decimal,
			SOR_TOTAL_DISCOUNT     ::decimal,
			SOR_TOTAL_TAX          ::decimal,
			SOR_TAX_CODE                   ::VARCHAR(30),
			SOR_TAX_SUBCODE                ::VARCHAR(30),
			SOR_TAX_PERCENT                ::decimal,
			SOR_CST_ACCOUNT        ::VARCHAR(30),
			SOR_CST_SITE_ID        ::VARCHAR(30),
			SOR_CUSTOMER_MOBILE            ::VARCHAR(30),
			SOR_CREDIT_LIMIT       ::decimal,
			SOR_PAYMENT_TERM       ::decimal,
			SOR_ORDER_NOTE                 ::VARCHAR(2000),
			SOR_APPROVAL_STATUS            ::VARCHAR(30),
			SOR_CREDIT_REQUESTED           ::decimal,
			SOR_REQUEST_STATUS             ::VARCHAR(30),
			SOR_CHECKED_TIME               ::VARCHAR(30),
			SOR_ORDER_OTP                  ::VARCHAR(30),
			SOR_OTP_STATUS                 ::VARCHAR(30),
			SOR_CST_SIGNATURE              ::VARCHAR(300),
			SOR_CREATED_DEVICE     ::VARCHAR(30),
			SOR_DEVICE_MODE        ::VARCHAR(30),
			SOR_ORDER_SOURCE               ::VARCHAR(30),
			SOR_REFERENCE_NO               ::VARCHAR(30),
			PFI_ID_SEQ                     ::bigint,
			SOR_DELIVERED_STATUS           ::VARCHAR(30),
			SOR_DELIVERED_TIME             ::VARCHAR(30),
			SOR_RECEIPT_NO                 ::VARCHAR(30),
			SOR_RECEIPT_VALUE              ::decimal,
			SOR_RECEIPT_DISCOUNT           ::decimal,
			SOR_RECEIPT_TAX                ::decimal,
			SOR_RECEIPT_PRint              ::smallint,
			SOR_RECEIPT_COPY               ::VARCHAR(300),
			SOR_IS_PRIORITY                ::VARCHAR(30),
			SOR_INTERFACE_STATUS           ::VARCHAR(30),
			SOR_INTERFACE_TRXID            ::VARCHAR(30),
			SOR_INTERFACE_NOTE             ::VARCHAR(2000),
			SOR_INTERFACE_DATE             ::VARCHAR(30),
			CUR_SEQ                ::smallint,
			CNT_SEQ                ::smallint,
			SOR_COLLECTION_STATUS  ::VARCHAR(30),
			SOR_COLLECTED_AMT              ::decimal,
			cast(CREATED_DATE as timestamp) AS CREATED_DATE,
			CREATED_USER          ::smallint,
			cast(UPDATED_DATE as timestamp) AS UPDATED_DATE,
			UPDATED_USER           ::smallint,
			ATTRIBUTE1                     ::VARCHAR(100),
			ATTRIBUTE2                     ::VARCHAR(100),
			ATTRIBUTE3                     ::VARCHAR(100),
			ATTRIBUTE4                     ::VARCHAR(100),
			ATTRIBUTE5                     ::VARCHAR(100),
			ATTRIBUTE6                     ::VARCHAR(100),
			ATTRIBUTE7                     ::VARCHAR(100),
			ATTRIBUTE8                     ::VARCHAR(100),
			ATTRIBUTE9                     ::VARCHAR(100),
			ATTRIBUTE10                    ::VARCHAR(100),
			ATTRIBUTE11                    ::VARCHAR(100),
			ATTRIBUTE12                    ::VARCHAR(100),
			ATTRIBUTE13                    ::VARCHAR(100),
			ATTRIBUTE14                    ::VARCHAR(100),
			ATTRIBUTE15                    ::VARCHAR(100),
			 CREATE_MONTH ::smallint,
			CREATE_YEAR ::smallint,
			case when row_number() over(partition by SOR_ID_SEQ order by UPDATED_DATE desc) = 1 then 'A'
			 else 'X' end as Active_flag
			from om_stage.OM_SALES_ORDER_recon
			where SOR_ORDER_NO in (select SOR_ORDER_NO from om_stage.om_sales_orders_recon_temp)  and
  SOR_ORDER_NO not in (select SOR_ORDER_NO from om_dbo.OM_SALES_ORDER ord)) ;
